# Generated by Django 3.0.5 on 2020-08-15 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255, verbose_name='Categoria')),
                ('status', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id_paper', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('publication_year', models.DateField(verbose_name='Fecha de publicacion')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('viewed', models.IntegerField()),
                ('downloads', models.IntegerField()),
                ('pos_rate', models.IntegerField()),
                ('neg_rate', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Papers',
                'verbose_name_plural': 'Paper',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('password', models.CharField(max_length=40, verbose_name='Contraseña')),
                ('status', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PapersUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paper', models.IntegerField()),
                ('rated', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperflix.Users')),
            ],
            options={
                'verbose_name': 'Paper',
                'verbose_name_plural': 'Papers',
            },
        ),
        migrations.CreateModel(
            name='CategoryPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperflix.Categories')),
                ('id_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperflix.Papers')),
            ],
        ),
    ]
