# Generated by Django 3.0.5 on 2020-08-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('status', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
        ),
    ]
