# Generated by Django 3.0.5 on 2020-10-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersuser',
            name='type_user',
            field=models.CharField(default='user', max_length=10, verbose_name='Tipo de Usuario'),
            preserve_default=False,
        ),
    ]
