# Generated by Django 3.0.5 on 2020-09-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersuser',
            name='id_paper',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='papersuser',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
