# Generated by Django 3.0.5 on 2020-09-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflix', '0002_adminusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=255, unique=True, verbose_name='Categoria'),
        ),
    ]
