# Generated by Django 3.0.5 on 2020-10-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperflix', '0002_papersuser_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papersuser',
            name='type_user',
        ),
        migrations.AddField(
            model_name='cookies',
            name='type_user',
            field=models.CharField(default='user', max_length=10, verbose_name='Tipo de Usuario'),
            preserve_default=False,
        ),
    ]
