# Generated by Django 3.0.5 on 2020-09-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperflix', '0003_auto_20200908_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papersuser',
            old_name='rated',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='neg_rate',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='number_pages',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='pos_rate',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='viewed',
        ),
    ]
